### PR TITLE
systemctl service file

### PR DESCRIPTION
**Pull request by AugustH**
Took me a while to auto-start it with systemctl. Maybe this save same work for the next users.

### CODE REVIEW

**Comment by AugustH** [comment]
Is this ok to include? another possibility would be to include this service file and an inginious.service into the INGInious documentation.

**Comment by anthonygego** [comment]
It's ok to include I guess.

Can you sign the CLA ? The repo was not not linked to CLA-assistant.
https://cla-assistant.io/UCL-INGI/INGInious-xterm

Thanks.

**Comment by AugustH** [comment]
is it enough to "sign via github" or do you need a physical copy or a scanned signed printout?

**Comment by anthonygego** [comment]
It's enough with Github signing. Thanks.

**Pull request merged**
